import { AlertTriangle } from 'lucide-react';
import { cn } from '@/lib/utils';

interface ClinicalDisclaimerProps {
  variant?: 'footer' | 'consent' | 'emergency';
  className?: string;
}

export function ClinicalDisclaimer({ variant = 'footer', className }: ClinicalDisclaimerProps) {
  if (variant === 'footer') {
    return (
      <div className={cn('bg-muted/50 border-t border-border px-4 py-3', className)}>
        <p className="text-xs text-muted-foreground text-center max-w-4xl mx-auto">
          <strong>Disclaimer:</strong> This system is an AI-powered clinical decision support tool 
          intended to assist healthcare professionals. It does not provide a medical diagnosis and 
          should not be used as a substitute for professional clinical judgment, examination, or 
          standard diagnostic procedures.
        </p>
      </div>
    );
  }

  if (variant === 'consent') {
    return (
      <div className={cn('bg-risk-medium/5 border border-risk-medium/20 rounded-lg p-4', className)}>
        <div className="flex gap-3">
          <AlertTriangle className="w-5 h-5 text-risk-medium flex-shrink-0 mt-0.5" />
          <div className="space-y-2">
            <h4 className="font-semibold text-foreground">Important Notice</h4>
            <p className="text-sm text-muted-foreground">
              The predictions and visualizations generated by this platform are based on machine 
              learning models trained on retrospective medical data. Results are intended to support 
              clinical assessment and triage only.
            </p>
            <p className="text-sm text-muted-foreground">
              This system does not diagnose diseases, prescribe treatment, or replace licensed 
              medical professionals. Final clinical decisions must be made by qualified healthcare 
              providers after appropriate examination and review of patient history.
            </p>
            <p className="text-sm font-medium text-foreground">
              By proceeding, you acknowledge that this tool is used for decision support purposes only.
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (variant === 'emergency') {
    return (
      <div className={cn('bg-risk-high/5 border border-risk-high/20 rounded-lg p-4', className)}>
        <div className="flex gap-3">
          <AlertTriangle className="w-5 h-5 text-risk-high flex-shrink-0" />
          <p className="text-sm text-foreground">
            <strong>Emergency Notice:</strong> In emergency situations, always seek immediate medical 
            attention. This platform is not designed for real-time emergency diagnosis or treatment.
          </p>
        </div>
      </div>
    );
  }

  return null;
}
